#############################################################################
# Makefile for building: sph17
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  sph17.pro
# Template: app
# Command: /opt/qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile sph17.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/alembic-1.5.8/include -Iinclude -I/usr/local/include/OpenEXR -I/home/i7611774/NGL/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore -Imoc -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sph171.0.0
DISTDIR = /home/i7611774/Desktop/MastersProject/sph17/obj/sph171.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt/5.5/gcc_64 -Wl,-rpath,/home/i7611774/Desktop/MastersProject/sph17/L/home/i7611774/NGL/lib -Wl,-rpath,/home/i7611774/NGL/lib -Wl,-rpath,/opt/qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/alembic-1.5.8/lib/static -lAbcWFObjConvert -lAlembicAbcCoreOgawa -lAlembicAbc -lAlembicAbcGeom -lAlembicAbcCollection -lAlembicAbcMaterial -lAlembicAbcCoreAbstract -lAlembicAbcOpenGL -lAlembicAbcCoreFactory -lAlembicOgawa -lAlembicAbcCoreHDF5 -lAlembicUtil -L/usr/local/lib -lHalf -L/home/i7611774/NGL/lib -l NGL -ltiff -L/opt/qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Globals.cpp \
		src/main.cpp \
		src/NGLScene.cpp \
		src/Particle.cpp \
		src/System.cpp \
		src/Tank.cpp 
OBJECTS       = obj/Globals.o \
		obj/main.o \
		obj/NGLScene.o \
		obj/Particle.o \
		obj/System.o \
		obj/Tank.o
DIST          = sph17.pro include/Globals.h \
		include/NGLScene.h \
		include/Particle.h \
		include/System.h \
		include/Tank.h src/Globals.cpp \
		src/main.cpp \
		src/NGLScene.cpp \
		src/Particle.cpp \
		src/System.cpp \
		src/Tank.cpp
QMAKE_TARGET  = sph17
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = sph17


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sph17.pro .qmake.cache /opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/i7611774/NGL/UseNGL.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf \
		sph17.pro \
		/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sph17.pro
/opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
/home/i7611774/NGL/UseNGL.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf:
sph17.pro:
/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sph17.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/Globals.h include/NGLScene.h include/Particle.h include/System.h include/Tank.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Globals.cpp src/main.cpp src/NGLScene.cpp src/Particle.cpp src/System.cpp src/Tank.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/Globals.o: src/Globals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Globals.o src/Globals.cpp

obj/main.o: src/main.cpp /opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		include/NGLScene.h \
		include/Globals.h \
		/home/i7611774/NGL/include/ngl/Camera.h \
		/home/i7611774/NGL/include/ngl/Types.h \
		/home/i7611774/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7611774/NGL/include/ngl/Vec4.h \
		/home/i7611774/NGL/include/ngl/Vec2.h \
		/home/i7611774/NGL/include/ngl/Vec3.h \
		/home/i7611774/NGL/include/ngl/Mat4.h \
		/home/i7611774/NGL/include/ngl/RibExport.h \
		/home/i7611774/NGL/include/ngl/Plane.h \
		/home/i7611774/NGL/include/ngl/AABB.h \
		/home/i7611774/NGL/include/ngl/BBox.h \
		/home/i7611774/NGL/include/ngl/AbstractVAO.h \
		/home/i7611774/NGL/include/ngl/Colour.h \
		/home/i7611774/NGL/include/ngl/Light.h \
		/home/i7611774/NGL/include/ngl/Text.h \
		/home/i7611774/NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		include/System.h \
		include/Particle.h \
		include/Tank.h \
		/home/i7611774/NGL/include/ngl/VAOPrimitives.h \
		/home/i7611774/NGL/include/ngl/Singleton.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ArchiveBounds.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Base.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Foundation.h \
		/usr/local/include/OpenEXR/half.h \
		/usr/local/include/OpenEXR/halfExport.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Digest.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/PlainOldDataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Exception.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Dimensions.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Murmur3.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Naming.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/OperatorBool.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/TokenMap.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/SpookyV2.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ForwardDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/PropertyHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/MetaData.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/DataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSampling.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSamplingType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySampleKey.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ReadArraySampleCache.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarSample.h \
		/usr/local/include/OpenEXR/ImathVec.h \
		/usr/local/include/OpenEXR/ImathExc.h \
		/usr/local/include/OpenEXR/ImathNamespace.h \
		/usr/local/include/OpenEXR/IlmBaseConfig.h \
		/usr/local/include/OpenEXR/IexBaseExc.h \
		/usr/local/include/OpenEXR/IexNamespace.h \
		/usr/local/include/OpenEXR/IexExport.h \
		/usr/local/include/OpenEXR/ImathExport.h \
		/usr/local/include/OpenEXR/ImathLimits.h \
		/usr/local/include/OpenEXR/ImathMath.h \
		/usr/local/include/OpenEXR/ImathPlatform.h \
		/usr/local/include/OpenEXR/ImathBox.h \
		/usr/local/include/OpenEXR/ImathMatrix.h \
		/usr/local/include/OpenEXR/ImathFun.h \
		/usr/local/include/OpenEXR/ImathInt64.h \
		/usr/local/include/OpenEXR/ImathShear.h \
		/usr/local/include/OpenEXR/ImathQuat.h \
		/usr/local/include/OpenEXR/ImathColor.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ErrorHandler.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ArchiveInfo.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Argument.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISampleSelector.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ICompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OCompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedPropertyTraits.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Reference.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/SourceName.h \
		/usr/local/include/OpenEXR/ImathMatrixAlgo.h \
		/usr/local/include/OpenEXR/ImathEuler.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/GeometryScope.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Basis.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CurveType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/SchemaInfoDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FaceSetExclusivity.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FilmBackXformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CameraSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ILight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OLight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/INuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ONuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OSubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ISubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Visibility.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/ReadWrite.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QTime \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatetime.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QObject \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtCore/QMargins \
		/opt/qt/5.5/gcc_64/include/QtCore/QRect \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/NGLScene.o: src/NGLScene.cpp /opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QMouseEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		include/Globals.h \
		include/NGLScene.h \
		/home/i7611774/NGL/include/ngl/Camera.h \
		/home/i7611774/NGL/include/ngl/Types.h \
		/home/i7611774/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7611774/NGL/include/ngl/Vec4.h \
		/home/i7611774/NGL/include/ngl/Vec2.h \
		/home/i7611774/NGL/include/ngl/Vec3.h \
		/home/i7611774/NGL/include/ngl/Mat4.h \
		/home/i7611774/NGL/include/ngl/RibExport.h \
		/home/i7611774/NGL/include/ngl/Plane.h \
		/home/i7611774/NGL/include/ngl/AABB.h \
		/home/i7611774/NGL/include/ngl/BBox.h \
		/home/i7611774/NGL/include/ngl/AbstractVAO.h \
		/home/i7611774/NGL/include/ngl/Colour.h \
		/home/i7611774/NGL/include/ngl/Light.h \
		/home/i7611774/NGL/include/ngl/Text.h \
		/home/i7611774/NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		include/System.h \
		include/Particle.h \
		include/Tank.h \
		/home/i7611774/NGL/include/ngl/VAOPrimitives.h \
		/home/i7611774/NGL/include/ngl/Singleton.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ArchiveBounds.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Base.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Foundation.h \
		/usr/local/include/OpenEXR/half.h \
		/usr/local/include/OpenEXR/halfExport.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Digest.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/PlainOldDataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Exception.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Dimensions.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Murmur3.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Naming.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/OperatorBool.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/TokenMap.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/SpookyV2.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ForwardDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/PropertyHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/MetaData.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/DataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSampling.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSamplingType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySampleKey.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ReadArraySampleCache.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarSample.h \
		/usr/local/include/OpenEXR/ImathVec.h \
		/usr/local/include/OpenEXR/ImathExc.h \
		/usr/local/include/OpenEXR/ImathNamespace.h \
		/usr/local/include/OpenEXR/IlmBaseConfig.h \
		/usr/local/include/OpenEXR/IexBaseExc.h \
		/usr/local/include/OpenEXR/IexNamespace.h \
		/usr/local/include/OpenEXR/IexExport.h \
		/usr/local/include/OpenEXR/ImathExport.h \
		/usr/local/include/OpenEXR/ImathLimits.h \
		/usr/local/include/OpenEXR/ImathMath.h \
		/usr/local/include/OpenEXR/ImathPlatform.h \
		/usr/local/include/OpenEXR/ImathBox.h \
		/usr/local/include/OpenEXR/ImathMatrix.h \
		/usr/local/include/OpenEXR/ImathFun.h \
		/usr/local/include/OpenEXR/ImathInt64.h \
		/usr/local/include/OpenEXR/ImathShear.h \
		/usr/local/include/OpenEXR/ImathQuat.h \
		/usr/local/include/OpenEXR/ImathColor.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ErrorHandler.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ArchiveInfo.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Argument.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISampleSelector.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ICompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OCompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedPropertyTraits.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Reference.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/SourceName.h \
		/usr/local/include/OpenEXR/ImathMatrixAlgo.h \
		/usr/local/include/OpenEXR/ImathEuler.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/GeometryScope.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Basis.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CurveType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/SchemaInfoDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FaceSetExclusivity.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FilmBackXformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CameraSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ILight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OLight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/INuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ONuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OSubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ISubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Visibility.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/ReadWrite.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QTime \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatetime.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QObject \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtCore/QMargins \
		/opt/qt/5.5/gcc_64/include/QtCore/QRect \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QImage \
		/home/i7611774/NGL/include/ngl/Material.h \
		/home/i7611774/NGL/include/ngl/NGLInit.h \
		/home/i7611774/NGL/include/ngl/ShaderLib.h \
		/home/i7611774/NGL/include/ngl/Shader.h \
		/home/i7611774/NGL/include/ngl/ShaderProgram.h \
		/home/i7611774/NGL/include/ngl/Util.h \
		/home/i7611774/NGL/include/ngl/Mat3.h \
		/home/i7611774/NGL/include/ngl/Transformation.h \
		/home/i7611774/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/Particle.o: src/Particle.cpp include/Particle.h \
		include/Globals.h \
		/home/i7611774/NGL/include/ngl/Vec3.h \
		/home/i7611774/NGL/include/ngl/Types.h \
		/home/i7611774/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7611774/NGL/include/ngl/Colour.h \
		include/Tank.h \
		/home/i7611774/NGL/include/ngl/VAOPrimitives.h \
		/home/i7611774/NGL/include/ngl/Singleton.h \
		/home/i7611774/NGL/include/ngl/VertexArrayObject.h \
		/home/i7611774/NGL/include/ngl/Camera.h \
		/home/i7611774/NGL/include/ngl/Vec4.h \
		/home/i7611774/NGL/include/ngl/Vec2.h \
		/home/i7611774/NGL/include/ngl/Mat4.h \
		/home/i7611774/NGL/include/ngl/RibExport.h \
		/home/i7611774/NGL/include/ngl/Plane.h \
		/home/i7611774/NGL/include/ngl/AABB.h \
		/home/i7611774/NGL/include/ngl/BBox.h \
		/home/i7611774/NGL/include/ngl/AbstractVAO.h \
		/home/i7611774/NGL/include/ngl/Random.h \
		/home/i7611774/NGL/include/ngl/ShaderLib.h \
		/home/i7611774/NGL/include/ngl/Shader.h \
		/home/i7611774/NGL/include/ngl/ShaderProgram.h \
		/home/i7611774/NGL/include/ngl/Util.h \
		/home/i7611774/NGL/include/ngl/Mat3.h \
		/home/i7611774/NGL/include/ngl/Transformation.h \
		/home/i7611774/NGL/include/ngl/NGLassert.h \
		/home/i7611774/NGL/include/ngl/Light.h \
		/home/i7611774/NGL/include/ngl/Material.h \
		include/System.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ArchiveBounds.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Base.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Foundation.h \
		/usr/local/include/OpenEXR/half.h \
		/usr/local/include/OpenEXR/halfExport.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Digest.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/PlainOldDataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Exception.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Dimensions.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Murmur3.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Naming.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/OperatorBool.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/TokenMap.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/SpookyV2.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ForwardDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/PropertyHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/MetaData.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/DataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSampling.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSamplingType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySampleKey.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ReadArraySampleCache.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarSample.h \
		/usr/local/include/OpenEXR/ImathVec.h \
		/usr/local/include/OpenEXR/ImathExc.h \
		/usr/local/include/OpenEXR/ImathNamespace.h \
		/usr/local/include/OpenEXR/IlmBaseConfig.h \
		/usr/local/include/OpenEXR/IexBaseExc.h \
		/usr/local/include/OpenEXR/IexNamespace.h \
		/usr/local/include/OpenEXR/IexExport.h \
		/usr/local/include/OpenEXR/ImathExport.h \
		/usr/local/include/OpenEXR/ImathLimits.h \
		/usr/local/include/OpenEXR/ImathMath.h \
		/usr/local/include/OpenEXR/ImathPlatform.h \
		/usr/local/include/OpenEXR/ImathBox.h \
		/usr/local/include/OpenEXR/ImathMatrix.h \
		/usr/local/include/OpenEXR/ImathFun.h \
		/usr/local/include/OpenEXR/ImathInt64.h \
		/usr/local/include/OpenEXR/ImathShear.h \
		/usr/local/include/OpenEXR/ImathQuat.h \
		/usr/local/include/OpenEXR/ImathColor.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ErrorHandler.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ArchiveInfo.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Argument.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISampleSelector.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ICompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OCompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedPropertyTraits.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Reference.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/SourceName.h \
		/usr/local/include/OpenEXR/ImathMatrixAlgo.h \
		/usr/local/include/OpenEXR/ImathEuler.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/GeometryScope.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Basis.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CurveType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/SchemaInfoDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FaceSetExclusivity.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FilmBackXformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CameraSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ILight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OLight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/INuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ONuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OSubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ISubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Visibility.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/ReadWrite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Particle.o src/Particle.cpp

obj/System.o: src/System.cpp include/System.h \
		include/Globals.h \
		/home/i7611774/NGL/include/ngl/Vec3.h \
		/home/i7611774/NGL/include/ngl/Types.h \
		/home/i7611774/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7611774/NGL/include/ngl/Camera.h \
		/home/i7611774/NGL/include/ngl/Vec4.h \
		/home/i7611774/NGL/include/ngl/Vec2.h \
		/home/i7611774/NGL/include/ngl/Mat4.h \
		/home/i7611774/NGL/include/ngl/RibExport.h \
		/home/i7611774/NGL/include/ngl/Plane.h \
		/home/i7611774/NGL/include/ngl/AABB.h \
		/home/i7611774/NGL/include/ngl/BBox.h \
		/home/i7611774/NGL/include/ngl/AbstractVAO.h \
		include/Particle.h \
		/home/i7611774/NGL/include/ngl/Colour.h \
		include/Tank.h \
		/home/i7611774/NGL/include/ngl/VAOPrimitives.h \
		/home/i7611774/NGL/include/ngl/Singleton.h \
		/home/i7611774/NGL/include/ngl/VertexArrayObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ArchiveBounds.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Base.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/Foundation.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Foundation.h \
		/usr/local/include/OpenEXR/half.h \
		/usr/local/include/OpenEXR/halfExport.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Digest.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/PlainOldDataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Exception.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Dimensions.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Murmur3.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/Naming.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/OperatorBool.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/TokenMap.h \
		/usr/local/alembic-1.5.8/include/Alembic/Util/SpookyV2.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ForwardDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/PropertyHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/MetaData.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/DataType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSampling.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/TimeSamplingType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArraySampleKey.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ReadArraySampleCache.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArchiveWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ArrayPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/BasePropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/CompoundPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectHeader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ObjectWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyReader.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarPropertyWriter.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreAbstract/ScalarSample.h \
		/usr/local/include/OpenEXR/ImathVec.h \
		/usr/local/include/OpenEXR/ImathExc.h \
		/usr/local/include/OpenEXR/ImathNamespace.h \
		/usr/local/include/OpenEXR/IlmBaseConfig.h \
		/usr/local/include/OpenEXR/IexBaseExc.h \
		/usr/local/include/OpenEXR/IexNamespace.h \
		/usr/local/include/OpenEXR/IexExport.h \
		/usr/local/include/OpenEXR/ImathExport.h \
		/usr/local/include/OpenEXR/ImathLimits.h \
		/usr/local/include/OpenEXR/ImathMath.h \
		/usr/local/include/OpenEXR/ImathPlatform.h \
		/usr/local/include/OpenEXR/ImathBox.h \
		/usr/local/include/OpenEXR/ImathMatrix.h \
		/usr/local/include/OpenEXR/ImathFun.h \
		/usr/local/include/OpenEXR/ImathInt64.h \
		/usr/local/include/OpenEXR/ImathShear.h \
		/usr/local/include/OpenEXR/ImathQuat.h \
		/usr/local/include/OpenEXR/ImathColor.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ErrorHandler.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ArchiveInfo.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Argument.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArchive.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISampleSelector.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ICompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/IScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchema.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OCompoundProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OBaseProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ISchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedPropertyTraits.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/TypedArraySample.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/ITypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OSchemaObject.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedArrayProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/OTypedScalarProperty.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/Reference.h \
		/usr/local/alembic-1.5.8/include/Alembic/Abc/SourceName.h \
		/usr/local/include/OpenEXR/ImathMatrixAlgo.h \
		/usr/local/include/OpenEXR/ImathEuler.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/GeometryScope.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Basis.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CurveType.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/SchemaInfoDeclarations.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICurves.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomParam.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IGeomBase.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FaceSetExclusivity.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IFaceSet.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/FilmBackXformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/CameraSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OCamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ICamera.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ILight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OLight.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/INuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ONuPatch.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPoints.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IPolyMesh.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OSubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/ISubD.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformOp.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/XformSample.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/OXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/IXform.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcGeom/Visibility.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/All.h \
		/usr/local/alembic-1.5.8/include/Alembic/AbcCoreOgawa/ReadWrite.h \
		/home/i7611774/NGL/include/ngl/Random.h \
		/home/i7611774/NGL/include/ngl/Transformation.h \
		/home/i7611774/NGL/include/ngl/NGLassert.h \
		/home/i7611774/NGL/include/ngl/ShaderLib.h \
		/home/i7611774/NGL/include/ngl/Shader.h \
		/home/i7611774/NGL/include/ngl/ShaderProgram.h \
		/home/i7611774/NGL/include/ngl/Util.h \
		/home/i7611774/NGL/include/ngl/Mat3.h \
		/home/i7611774/NGL/include/ngl/Logger.h \
		/home/i7611774/NGL/include/ngl/NGLStream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QElapsedTimer \
		/opt/qt/5.5/gcc_64/include/QtCore/qelapsedtimer.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/System.o src/System.cpp

obj/Tank.o: src/Tank.cpp include/Tank.h \
		include/Globals.h \
		/home/i7611774/NGL/include/ngl/VAOPrimitives.h \
		/home/i7611774/NGL/include/ngl/Singleton.h \
		/home/i7611774/NGL/include/ngl/Types.h \
		/home/i7611774/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7611774/NGL/include/ngl/Vec3.h \
		/home/i7611774/NGL/include/ngl/VertexArrayObject.h \
		/home/i7611774/NGL/include/ngl/Camera.h \
		/home/i7611774/NGL/include/ngl/Vec4.h \
		/home/i7611774/NGL/include/ngl/Vec2.h \
		/home/i7611774/NGL/include/ngl/Mat4.h \
		/home/i7611774/NGL/include/ngl/RibExport.h \
		/home/i7611774/NGL/include/ngl/Plane.h \
		/home/i7611774/NGL/include/ngl/AABB.h \
		/home/i7611774/NGL/include/ngl/BBox.h \
		/home/i7611774/NGL/include/ngl/AbstractVAO.h \
		/home/i7611774/NGL/include/ngl/Light.h \
		/home/i7611774/NGL/include/ngl/Colour.h \
		/home/i7611774/NGL/include/ngl/Material.h \
		/home/i7611774/NGL/include/ngl/NGLInit.h \
		/home/i7611774/NGL/include/ngl/ShaderLib.h \
		/home/i7611774/NGL/include/ngl/Shader.h \
		/home/i7611774/NGL/include/ngl/ShaderProgram.h \
		/home/i7611774/NGL/include/ngl/Util.h \
		/home/i7611774/NGL/include/ngl/Mat3.h \
		/home/i7611774/NGL/include/ngl/Transformation.h \
		/home/i7611774/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tank.o src/Tank.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

